'use client';

interface ReasoningPanelProps {
  data: any | null;
  isLoading: boolean;
}

export default function ReasoningPanel({ data, isLoading }: ReasoningPanelProps) {
  if (isLoading) {
    return (
      <div className="reasoning-panel glass" style={{ padding: '2rem', height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', gap: '1rem' }}>
        <div className="spinner" style={{ width: '40px', height: '40px', border: '3px solid rgba(137, 87, 229, 0.2)', borderTopColor: 'var(--primary)', borderRadius: '50%', animation: 'spin 1s linear infinite' }}></div>
        <div style={{ color: 'var(--text-muted)' }}>Engaging Reasoning Substrate...</div>
        <style dangerouslySetInnerHTML={{ __html: `@keyframes spin { to { transform: rotate(360deg); } }` }} />
      </div>
    );
  }

  if (!data) {
    return (
      <div className="reasoning-panel glass" style={{ padding: '2rem', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', color: 'var(--text-muted)', border: '1px dashed var(--border-color)', borderRadius: '12px' }}>
        No analysis data. Waiting for instruction...
      </div>
    );
  }

  const { thesis, action_plan, next_steps } = data;

  return (
    <div className="reasoning-panel glass" style={{
      padding: '2rem',
      borderRadius: '12px',
      height: '100%',
      overflowY: 'auto'
    }}>
      <header style={{ marginBottom: '2rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' }}>
        <h2 style={{ fontSize: '1.25rem', marginBottom: '0.5rem' }}>Intelligence Output</h2>
        <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          Generated by <strong>Hermes-v1</strong> · Confidence: 
          <span style={{ marginLeft: '0.5rem', fontWeight: 'bold', color: thesis.confidence > 0.8 ? 'var(--success)' : 'var(--warn)' }}>
            {Math.round(thesis.confidence * 100)}%
          </span>
        </div>
      </header>

      {/* 1. Executive Summary */}
      <section style={{ marginBottom: '2rem' }}>
        <h3 style={{ fontSize: '0.9rem', color: 'var(--primary-hover)', marginBottom: '0.75rem', textTransform: 'uppercase', letterSpacing: '1px' }}>Executive Summary</h3>
        <p style={{ fontSize: '1.1rem', lineHeight: '1.6', fontWeight: '500' }}>{thesis.summary}</p>
      </section>

      {/* 2. Key Findings */}
      {thesis.key_findings && (
        <section style={{ marginBottom: '2rem' }}>
          <h3 style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>KEY FINDINGS</h3>
          <ul style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', paddingLeft: '1.2rem' }}>
            {thesis.key_findings.map((f: string, i: number) => <li key={i}>{f}</li>)}
          </ul>
        </section>
      )}

      {/* 3. Symmetric Evidence (Core Requirement) */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '2.5rem' }}>
        <section>
          <h3 style={{ fontSize: '0.75rem', fontWeight: '800', color: '#3fb950', marginBottom: '1rem', borderBottom: '2px solid rgba(63, 185, 80, 0.2)', paddingBottom: '4px' }}>
            PROS / SUPPORT
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {thesis.evidence_for.map((e: string, i: number) => (
              <li key={i} style={{ fontSize: '0.85rem', display: 'flex', gap: '8px' }}>
                <span style={{ color: '#3fb950' }}>✓</span> {e}
              </li>
            ))}
          </ul>
        </section>
        
        <section>
          <h3 style={{ fontSize: '0.75rem', fontWeight: '800', color: '#f85149', marginBottom: '1rem', borderBottom: '2px solid rgba(248, 81, 73, 0.2)', paddingBottom: '4px' }}>
            CONS / COUNTER-EVIDENCE
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {thesis.evidence_against.map((e: string, i: number) => (
              <li key={i} style={{ fontSize: '0.85rem', display: 'flex', gap: '8px' }}>
                <span style={{ color: '#f85149' }}>×</span> {e}
              </li>
            ))}
          </ul>
        </section>
      </div>

      {/* 4. Action Plan */}
      <section style={{ marginBottom: '2rem', padding: '1.5rem', background: 'rgba(137, 87, 229, 0.05)', borderRadius: '8px', border: '1px solid rgba(137, 87, 229, 0.1)' }}>
        <h3 style={{ fontSize: '0.85rem', color: 'var(--primary-hover)', marginBottom: '1rem' }}>EXPLANATORY ACTION PLAN</h3>
        <div style={{ display: 'flex', gap: '2rem' }}>
          <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Action</div>
            <div style={{ fontWeight: 'bold', fontSize: '1.25rem', textTransform: 'capitalize' }}>{action_plan.action}</div>
          </div>
          <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Size</div>
            <div style={{ fontWeight: 'bold', fontSize: '1.25rem' }}>{action_plan.position_size_pct}%</div>
          </div>
        </div>
        <div style={{ marginTop: '1rem', fontSize: '0.8rem', fontStyle: 'italic', opacity: 0.8 }}>
          <strong>Invalidation:</strong> {action_plan.invalidation_condition}
        </div>
      </section>

      {/* 5. Next Steps */}
      <section>
        <h3 style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.75rem' }}>NEXT STRATEGIC STEPS</h3>
        <div style={{ fontSize: '0.85rem', color: 'var(--foreground)', paddingLeft: '0.5rem', borderLeft: '2px solid var(--border-color)' }}>
          {next_steps.map((s: string, i: number) => <div key={i} style={{ marginBottom: '4px' }}>• {s}</div>)}
        </div>
      </section>
    </div>
  );
}
